/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as employeeManagementSol from "./employeeManagement.sol";
export type { employeeManagementSol };
import type * as factorySol from "./factory.sol";
export type { factorySol };
import type * as interface from "./interface";
export type { interface };
export * as factories from "./factories";
export type { EmployeeManagement } from "./employeeManagement.sol/EmployeeManagement";
export { EmployeeManagement__factory } from "./factories/employeeManagement.sol/EmployeeManagement__factory";
export type { Factory } from "./factory.sol/Factory";
export { Factory__factory } from "./factories/factory.sol/Factory__factory";
export type { IEmployeeManagement } from "./interface/employeeManagement.sol/IEmployeeManagement";
export { IEmployeeManagement__factory } from "./factories/interface/employeeManagement.sol/IEmployeeManagement__factory";
