/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as employeeManagementSol from "./employeeManagement.sol";
export type { employeeManagementSol };
