/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as employeeManagementSol from "./employeeManagement.sol";
export * as factorySol from "./factory.sol";
export * as interface from "./interface";
