/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SchoolManagementSystem {
  export type StudentDetailsStruct = {
    addr: AddressLike;
    id: BigNumberish;
    name: string;
    course: string;
    age: BigNumberish;
    status: BigNumberish;
  };

  export type StudentDetailsStructOutput = [
    addr: string,
    id: bigint,
    name: string,
    course: string,
    age: bigint,
    status: bigint
  ] & {
    addr: string;
    id: bigint;
    name: string;
    course: string;
    age: bigint;
    status: bigint;
  };
}

export interface SchoolManagementSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "delete_student"
      | "get_all_students"
      | "get_student_by_address"
      | "register_student"
      | "students"
      | "update_student"
      | "update_students_status"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "delete_student",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_all_students",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "get_student_by_address",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register_student",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update_student",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update_students_status",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "delete_student",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_all_students",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_student_by_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "register_student",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "update_student",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "update_students_status",
    data: BytesLike
  ): Result;
}

export interface SchoolManagementSystem extends BaseContract {
  connect(runner?: ContractRunner | null): SchoolManagementSystem;
  waitForDeployment(): Promise<this>;

  interface: SchoolManagementSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delete_student: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  get_all_students: TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentDetailsStructOutput[]],
    "view"
  >;

  get_student_by_address: TypedContractMethod<
    [_addr: AddressLike],
    [SchoolManagementSystem.StudentDetailsStructOutput],
    "view"
  >;

  register_student: TypedContractMethod<
    [_addr: AddressLike, _name: string, _course: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        course: string;
        age: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  update_student: TypedContractMethod<
    [
      _addr: AddressLike,
      _new_name: string,
      _new_course: string,
      _new_age: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  update_students_status: TypedContractMethod<
    [_addr: AddressLike, _new_status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delete_student"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "get_all_students"
  ): TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_student_by_address"
  ): TypedContractMethod<
    [_addr: AddressLike],
    [SchoolManagementSystem.StudentDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "register_student"
  ): TypedContractMethod<
    [_addr: AddressLike, _name: string, _course: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        course: string;
        age: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "update_student"
  ): TypedContractMethod<
    [
      _addr: AddressLike,
      _new_name: string,
      _new_course: string,
      _new_age: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "update_students_status"
  ): TypedContractMethod<
    [_addr: AddressLike, _new_status: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
