/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as toDoListSol from "./ToDoList.sol";
export * as accessControlSol from "./accessControl.sol";
export * as mappingStudentMangementSol from "./mappingStudentMangement.sol";
