/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as toDoListSol from "./ToDoList.sol";
export type { toDoListSol };
import type * as accessControlSol from "./accessControl.sol";
export type { accessControlSol };
import type * as mappingStudentMangementSol from "./mappingStudentMangement.sol";
export type { mappingStudentMangementSol };
export * as factories from "./factories";
export type { AccessControl } from "./accessControl.sol/AccessControl";
export { AccessControl__factory } from "./factories/accessControl.sol/AccessControl__factory";
export type { SchoolManagementSystem } from "./mappingStudentMangement.sol/SchoolManagementSystem";
export { SchoolManagementSystem__factory } from "./factories/mappingStudentMangement.sol/SchoolManagementSystem__factory";
export type { TodoList } from "./ToDoList.sol/TodoList";
export { TodoList__factory } from "./factories/ToDoList.sol/TodoList__factory";
