/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fawazNftSol from "./FawazNFT.sol";
export type { fawazNftSol };
export type { Lock } from "./Lock";
