/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fawazNftSol from "./FawazNFT.sol";
export type { fawazNftSol };
import type * as lockSol from "./Lock.sol";
export type { lockSol };
