/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factorySol from "./factory.sol";
export type { factorySol };
import type * as multisigSol from "./multisig.sol";
export type { multisigSol };
export * as factories from "./factories";
export type { Factory } from "./factory.sol/Factory";
export { Factory__factory } from "./factories/factory.sol/Factory__factory";
export type { Multisig } from "./multisig.sol/Multisig";
export { Multisig__factory } from "./factories/multisig.sol/Multisig__factory";
