/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CHILD_TOKEN__factory } from "./CHILD_TOKEN__factory";
export { IERC20__factory } from "./IERC20__factory";
