/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC-20.sol";
export type { erc20Sol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { IBADAN_20 } from "./ERC-20.sol/IBADAN_20";
export { IBADAN_20__factory } from "./factories/ERC-20.sol/IBADAN_20__factory";
export type { IERC20 } from "./ERC-20.sol/IERC20";
export { IERC20__factory } from "./factories/ERC-20.sol/IERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
