/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBADAN_20 } from "./IBADAN_20";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { IBADAN_20__factory } from "./factories/IBADAN_20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
