/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC-20.sol";
export type { erc20Sol };
import type * as factorySol from "./factory.sol";
export type { factorySol };
export * as factories from "./factories";
export type { CHILD_TOKEN } from "./ERC-20.sol/CHILD_TOKEN";
export { CHILD_TOKEN__factory } from "./factories/ERC-20.sol/CHILD_TOKEN__factory";
export type { IERC20 } from "./ERC-20.sol/IERC20";
export { IERC20__factory } from "./factories/ERC-20.sol/IERC20__factory";
export type { ERC_20_FACTORY } from "./factory.sol/ERC_20_FACTORY";
export { ERC_20_FACTORY__factory } from "./factories/factory.sol/ERC_20_FACTORY__factory";
