/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBADAN_20__factory } from "./IBADAN_20__factory";
export { IERC20__factory } from "./IERC20__factory";
